"""
Pure-Python codegen: turns the JSON returned by /api/sdk/schemas into
a typed pydantic module the user imports in their app.

Each schema becomes a `hotlog.Event` subclass (which is itself a strict
pydantic BaseModel). Type mapping:

    STRING    -> str
    NUMBER    -> float
    BOOLEAN   -> bool
    DATETIME  -> datetime
    JSON      -> dict[str, Any]
    ARRAY     -> list[<itemType mapped recursively>]
    ENUM      -> Literal[...] (when enumValues are defined, else str)

Required fields stay non-optional. Optional fields become `T | None = None`.
Field descriptions and JSON aliases (for keys that aren't valid Python
identifiers) flow through `pydantic.Field(...)`.
"""

from __future__ import annotations

import json
import keyword
import re
from typing import Any

PRIMITIVE_MAP: dict[str, str] = {
    "STRING": "str",
    "NUMBER": "float",
    "BOOLEAN": "bool",
    "DATETIME": "datetime",
    "JSON": "dict[str, Any]",
}

_NON_IDENT = re.compile(r"[^0-9a-zA-Z_]+")


def to_class_name(key: str) -> str:
    """user_signup -> UserSignup"""
    parts = _NON_IDENT.sub("_", key).split("_")
    return "".join(p[:1].upper() + p[1:] for p in parts if p) or "Schema"


def safe_field_name(key: str) -> tuple[str, str | None]:
    """
    Return (python_name, alias_for_json) where alias is None if the
    field name is already a valid Python identifier.
    """
    candidate = _NON_IDENT.sub("_", key)
    if not candidate or candidate[0].isdigit():
        candidate = "_" + candidate
    if keyword.iskeyword(candidate):
        candidate += "_"
    return candidate, key if candidate != key else None


def render_type(field: dict[str, Any]) -> str:
    field_type = field.get("type", "STRING")
    metadata = field.get("metadata") or {}

    if field_type == "ENUM":
        values = metadata.get("enumValues") or []
        if values:
            literals = ", ".join(json.dumps(v) for v in values)
            return f"Literal[{literals}]"
        return "str"

    if field_type == "ARRAY":
        item_kind = (metadata.get("itemType") or "string").upper()
        return f"list[{PRIMITIVE_MAP.get(item_kind, 'Any')}]"

    return PRIMITIVE_MAP.get(field_type, "Any")


def _flatten_fields(schemas: list[dict[str, Any]]) -> list[dict[str, Any]]:
    return [f for s in schemas for f in (s.get("fields") or [])]


def _needs_datetime(schemas: list[dict[str, Any]]) -> bool:
    for f in _flatten_fields(schemas):
        if f.get("type") == "DATETIME":
            return True
        if f.get("type") == "ARRAY" and (f.get("metadata") or {}).get("itemType", "").upper() == "DATETIME":
            return True
    return False


def _needs_literal(schemas: list[dict[str, Any]]) -> bool:
    return any(
        f.get("type") == "ENUM" and (f.get("metadata") or {}).get("enumValues")
        for f in _flatten_fields(schemas)
    )


def _needs_any(schemas: list[dict[str, Any]]) -> bool:
    for f in _flatten_fields(schemas):
        if f.get("type") == "JSON":
            return True
        if f.get("type") == "ARRAY":
            kind = (f.get("metadata") or {}).get("itemType", "").upper()
            if kind not in PRIMITIVE_MAP:
                return True
    return False


HEADER = '''"""
Auto-generated by `uv run hotlog generate` — do NOT edit by hand.

Project: {project_name} ({project_id})
Schemas: {schema_count}

Re-run after changing schemas in the Hotlog dashboard.
"""

from __future__ import annotations

from typing import {typing_imports}
'''


def render_module(data: dict[str, Any]) -> str:
    project = data.get("project") or {}
    schemas = data.get("schemas") or []

    typing_imports = ["ClassVar"]
    if _needs_any(schemas):
        typing_imports.append("Any")
    if _needs_literal(schemas):
        typing_imports.append("Literal")

    out: list[str] = [
        HEADER.format(
            project_name=project.get("name", "(unknown)"),
            project_id=project.get("id", "(unknown)"),
            schema_count=len(schemas),
            typing_imports=", ".join(sorted(set(typing_imports))),
        )
    ]

    if _needs_datetime(schemas):
        out.append("from datetime import datetime")

    out.append("from pydantic import Field")
    out.append("")
    out.append("from hotlog import Event")
    out.append("")
    out.append("")

    if not schemas:
        out.append("# No active schemas defined for this project yet.")
        out.append("")
        return "\n".join(out)

    out.append("# Schema keys, useful for `client.send_raw(...)` calls.")
    out.append("class SchemaKeys:")
    for s in schemas:
        out.append(f"    {to_class_name(s['key'])} = {json.dumps(s['key'])}")
    out.append("")
    out.append("")

    for schema in schemas:
        out.extend(_render_schema_class(schema))
        out.append("")
        out.append("")

    return "\n".join(out).rstrip() + "\n"


def _render_schema_class(schema: dict[str, Any]) -> list[str]:
    cls = to_class_name(schema["key"])
    display = schema.get("displayName") or schema.get("name") or schema["key"]
    schema_key = schema["key"]
    fields = schema.get("fields") or []

    lines: list[str] = [
        f"class {cls}(Event):",
        f'    """{display} (schema_key: {schema_key})"""',
        "",
        f"    _hotlog_schema_key: ClassVar[str] = {json.dumps(schema_key)}",
    ]

    if not fields:
        return lines

    # Required first, then optional (Field(default=...) goes after non-defaults).
    required = [f for f in fields if f.get("required")]
    optional = [f for f in fields if not f.get("required")]

    lines.append("")
    for f in required + optional:
        lines.append(_render_field(f))

    return lines


def _render_field(f: dict[str, Any]) -> str:
    py_name, alias = safe_field_name(f["key"])
    py_type = render_type(f)
    metadata = f.get("metadata") or {}
    description = metadata.get("description")
    is_required = bool(f.get("required"))

    field_kwargs: list[str] = []
    if alias:
        field_kwargs.append(f"alias={json.dumps(alias)}")
    if description:
        field_kwargs.append(f"description={json.dumps(description)}")

    if is_required:
        if not field_kwargs:
            return f"    {py_name}: {py_type}"
        joined = ", ".join(field_kwargs)
        return f"    {py_name}: {py_type} = Field(..., {joined})"

    annotation = f"{py_type} | None"
    if not field_kwargs:
        return f"    {py_name}: {annotation} = None"
    joined = ", ".join(field_kwargs)
    return f"    {py_name}: {annotation} = Field(default=None, {joined})"
